name: scouts_mapping
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.7
  - pip
  # Core requirements
  - branca
  - dash
  - geopandas
  - numpy
  - pandas
  - shapely
  # Development requirements:
  - pytest
  - pytest-cov
  - pre-commit
  - black
  # Requirements not on conda:
  - pip:
    - folium
